<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DotnetLogShipper</RootNamespace>
    <Description>Sample log shipper using Sentinel.Sdk.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sdk\dotnet\Sentinel.Sdk\Sentinel.Sdk.csproj" />
  </ItemGroup>

</Project>
