apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.system }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    sentinel.io/namespace-tier: system
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.platform }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    sentinel.io/namespace-tier: platform
