{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.fullname" . }}-worker
  namespace: {{ .Values.namespaces.platform }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "sentinel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}
